require:
  - ./rules/my_scope/no_comments

MyScope/NoComments:
  Enabled: true
  AllowedPatterns:
    - '^NOTE: '

match-segments:
  - Pattern: wef
    Exclude:
      - '*_wef.yml'

match-file:
  - Pattern: German
    CaseSensitive: false
    Exclude:
      - '*de.yml'
