require:
  - ./rules/my_scope/no_comments

MyScope/NoComments:
  Enabled: true
  AllowedPatterns:
    - '^NOTE: '

BuiltIn/MatchSegment:
  Pattern: wef
BuiltIn/MatchFile:
  Pattern: German
  CaseSensitive: false
