AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - gemfiles/*.gemfile
    - spec/dummy/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FormatStringToken:
  Enabled: false # i18n has lots of false-positive %{name} placeholders

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - i18nlint.gemspec

Style/SignalException:
  Exclude:
    - spec/**/*_spec.rb # see rspec/matchers/fail_matchers
